config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gists

   root 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
    
  before_action :authenticate_user!
    
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  
  # GET /gists
  # GET /gists.json
  def index
@gists = Gist.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:imie, :nazwisko, :karnet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for @gist, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :imie, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :imie, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nazwisko, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nazwisko, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :karnet, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :karnet, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
        <%= f.submit "Zatwierdź", class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.usuń")),
                  gists_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/gists/edit.html.erb
<%- model_class = Gist -%>
<div class="page-header">
    <h1>Edytuj sprzedaż</h1>
</div>
<%= render partial: 'form' %>

app/views/gists/index.html.erb
<%- model_class = Gist -%>
<div class="page-header">

    <h2>Sprzedaż karnetów</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
        <th><%= model_class.human_attribute_name("Id") %></th>
      <th><%= model_class.human_attribute_name(:imie) %></th>
      <th><%= model_class.human_attribute_name(:nazwisko) %></th>
      <th><%= model_class.human_attribute_name(:karnet) %></th>
        <th><%= model_class.human_attribute_name("data sprzedaży") %></th>
        <th><%=t '.actions', default: t("helpers.Opcje") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gists.each do |gist| %>
      <tr>
        <td><%= gist.id %></td>
          <td><%= gist.imie %></td>
          <td><%= gist.nazwisko %></td>
          <td><%= gist.karnet %></td>
        <td><%=l gist.created_at, format: :long %></td>
        <td>
          <%= link_to gist_path(gist), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_gist_path(gist), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to gist_path(gist), method: :delete, data: { confirm: t('.confirm', default: t("Potwierdź usuwanie", default: 'Potwierdź usuwanie')) }, class: 'btn btn-xs', title: "Usuń klienta" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.dodaj")),
            new_gist_path,
            class: 'btn btn-primary' %>
<div class="text-center">
<%= will_paginate @gists %>
</div>

app/views/gists/new.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1>Nowa sprzedaż</h1>
</div>
<%= render partial: 'form' %>

app/views/gists/show.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1>Podgląd sprzedaży</h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imie) %></dt>
      <dd><pre class="prettyprint"><%= @gist.imie %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nazwisko) %></dt>
      <dd><pre class="prettyprint"><%= @gist.nazwisko %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:karnet) %></dt>
      <dd><pre class="prettyprint"><%= @gist.karnet %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.powrót")),
              gists_path, class: 'btn btn-default'  %>
    <%= link_to t('.edit', default: t("helpers.links.edytuj")),
              edit_gist_path(@gist), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.usuń")),
              gist_path(@gist),
              method: 'delete',
data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'czy na pewno chcesz usunąć tą sprzedaż?')) },
              class: 'btn btn-danger' %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sprzedane bilety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body>
    <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a href="/" class="navbar-brand"><%= t("Sprzedane karnety") %></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapsable">
      <ul class="nav navbar-nav foo" id="menu">
        <li class="active"><a href=""><%= t("Lista sprzedaży") %></a></li>
      </ul>
	  <center>
      <ul class="nav navbar-nav navbar-right" align="right">
			<% if user_signed_in? %>
				<li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "Zarejestruj", new_user_registration_path %></li>
			<li><%= link_to "Zaloguj", new_user_session_path %></li>   
			<% end %>
      </li>
	  </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>